const mongoose = require('mongoose');

const resourceSchema = new mongoose.Schema({
    title: {
        type: String,
        required: [true, 'Resource title is required'],
        trim: true,
        maxlength: [100, 'Title cannot exceed 100 characters']
    },
    description: {
        type: String,
        maxlength: [500, 'Description cannot exceed 500 characters']
    },
    // This stores the filename generated by Multer (e.g., user-123-timestamp.pdf)
    fileUrl: {
        type: String,
        required: [true, 'File is required']
    },
    // e.g., 'application/pdf', 'image/jpeg' - useful for UI icons
    fileType: {
        type: String
    },
    community: {
        type: mongoose.Schema.ObjectId,
        ref: 'Communities',
        required: true
    },
    author: {
        type: mongoose.Schema.ObjectId,
        ref: 'Users',
        required: true
    }
}, { timestamps: true });

module.exports = mongoose.model('Resources', resourceSchema);